import type { Metadata } from "next";
import "./globals.css";
import { Be_Vietnam_Pro } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import StoreProvider from "@/lib/StoreProvider";

const beVietnamPro = Be_Vietnam_Pro({
	subsets: ["vietnamese", "latin"],
	weight: ["400", "500", "600", "700"],
	variable: "--font-be-vietnam-pro",
});

export const metadata: Metadata = {
	title: "UIT Portal",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={beVietnamPro.className}>
				<StoreProvider>
					{children}
					<Toaster />
				</StoreProvider>
			</body>
		</html>
	);
}
